### ISSUE TITLE
[Bug 报告] 关于垂直于x轴的直线的处理问题

### ISSUE THREAD

**Issue by LAWArthur** [YuzhenQin/GeometryCalculator#2]
# 复现过程
如图，M为AB,AC交点(A)，但坐标计算发生浮点错误，且求解时程序无响应
<img width="789" alt="image" src="https://github.com/YuzhenQin/GeometryCalculator/assets/40540279/880c7fab-64ef-4c2e-a054-342ff374bc29">

# 解决方案
这是由于垂直于x轴的直线斜率为无穷大，无法使用点斜式表示。classes.py中Line的存储与计算从点斜式改为一般式即可解决（由于本人没有太多时间进行贡献故不提pull request）

**Comment by zhdbk3** [comment]
已修复
